# frozen_string_literal: true

require_relative "numeral/helpers"

require_relative "numeral/client.rb"
require_relative "numeral/configuration.rb"
require_relative "numeral/v1/balances/balance_id/show.rb"
require_relative "numeral/v1/balances/index.rb"
require_relative "numeral/v1/connected_accounts/account_id/show.rb"
require_relative "numeral/v1/connected_accounts/index.rb"
require_relative "numeral/v1/counterparties/counterparty_id/edit.rb"
require_relative "numeral/v1/counterparties/counterparty_id/show.rb"
require_relative "numeral/v1/counterparties/index.rb"
require_relative "numeral/v1/counterparties/new.rb"
require_relative "numeral/v1/counterparty_accounts/counterparty_account_id/edit.rb"
require_relative "numeral/v1/counterparty_accounts/counterparty_account_id/show.rb"
require_relative "numeral/v1/counterparty_accounts/index.rb"
require_relative "numeral/v1/counterparty_accounts/new.rb"
require_relative "numeral/v1/direct_debit_mandates/direct_debit_mandate_id/edit.rb"
require_relative "numeral/v1/direct_debit_mandates/direct_debit_mandate_id/show.rb"
require_relative "numeral/v1/direct_debit_mandates/index.rb"
require_relative "numeral/v1/direct_debit_mandates/new.rb"
require_relative "numeral/v1/files/file_id/edit.rb"
require_relative "numeral/v1/files/file_id/show.rb"
require_relative "numeral/v1/files/index.rb"
require_relative "numeral/v1/incoming_payments/incomin_payment_id/edit.rb"
require_relative "numeral/v1/incoming_payments/incomin_payment_id/show.rb"
require_relative "numeral/v1/incoming_payments/index.rb"
require_relative "numeral/v1/inquiries/index.rb"
require_relative "numeral/v1/inquiries/inquiry_id/edit.rb"
require_relative "numeral/v1/inquiries/inquiry_id/show.rb"
require_relative "numeral/v1/payment_orders/index.rb"
require_relative "numeral/v1/payment_orders/new.rb"
require_relative "numeral/v1/payment_orders/payment_order_id/edit.rb"
require_relative "numeral/v1/payment_orders/payment_order_id/show.rb"
require_relative "numeral/v1/return_requests/index.rb"
require_relative "numeral/v1/return_requests/new.rb"
require_relative "numeral/v1/return_requests/return_request_id/edit.rb"
require_relative "numeral/v1/return_requests/return_request_id/show.rb"
require_relative "numeral/v1/returns/index.rb"
require_relative "numeral/v1/returns/new.rb"
require_relative "numeral/v1/returns/return_id/show.rb"
require_relative "numeral/v1/transactions/index.rb"
require_relative "numeral/v1/transactions/transaction_id/show.rb"
require_relative "numeral/v1/virtual_accounts/index.rb"
require_relative "numeral/v1/virtual_accounts/new.rb"
require_relative "numeral/v1/virtual_accounts/virtual_account_id/counterparties/counterparty_id/edit.rb"
require_relative "numeral/v1/virtual_accounts/virtual_account_id/edit.rb"
require_relative "numeral/v1/virtual_accounts/virtual_account_id/show.rb"
require_relative "numeral/version.rb"

module Numeral
  class << self
    include Configuration
    include Client
  end
end
